export const elementDetails = {
  "H": {
    name: "Hydrogen",
    category: "diatomic nonmetal",
    block: "s",
    electronConfiguration: "1s1",
    valenceConfig: "1s1",
    electronegativity: 2.2,
    atomicRadius: 53,
    ionizationEnergy: 1312,
    electronAffinity: 72.769,
    oxidationStates: "",
    phase: "Gas",
    meltingPoint: 13.99,
    boilingPoint: 20.271,
    density: 0.08988,
    discoverer: "Henry Cavendish",
    summary: "Hydrogen is a chemical element with chemical symbol H and atomic number 1. With an atomic weight of 1.00794 u, hydrogen is the lightest element on the periodic table. Its monatomic form (H) is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass."
  },
  "He": {
    name: "Helium",
    category: "noble gas",
    block: "s",
    electronConfiguration: "1s2",
    valenceConfig: "[He]",
    electronegativity: null,
    atomicRadius: 31,
    ionizationEnergy: 2372.3,
    electronAffinity: -48,
    oxidationStates: "",
    phase: "Gas",
    meltingPoint: 0.95,
    boilingPoint: 4.222,
    density: 0.1786,
    discoverer: "Pierre Janssen",
    summary: "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas that heads the noble gas group in the periodic table. Its boiling and melting points are the lowest among all the elements."
  },
  "Li": {
    name: "Lithium",
    category: "alkali metal",
    block: "s",
    electronConfiguration: "1s2 2s1",
    valenceConfig: "[He] 2s1",
    electronegativity: 0.98,
    atomicRadius: 167,
    ionizationEnergy: 520.2,
    electronAffinity: 59.6326,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 453.65,
    boilingPoint: 1603,
    density: 0.534,
    discoverer: "Johan August Arfwedson",
    summary: "Lithium (from Greek:λίθος lithos, \"stone\") is a chemical element with the symbol Li and atomic number 3. It is a soft, silver-white metal belonging to the alkali metal group of chemical elements. Under standard conditions it is the lightest metal and the least dense solid element."
  },
  "Be": {
    name: "Beryllium",
    category: "alkaline earth metal",
    block: "s",
    electronConfiguration: "1s2 2s2",
    valenceConfig: "[He] 2s2",
    electronegativity: 1.57,
    atomicRadius: 112,
    ionizationEnergy: 899.5,
    electronAffinity: -48,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1560,
    boilingPoint: 2742,
    density: 1.85,
    discoverer: "Louis Nicolas Vauquelin",
    exception: "Ionization Energy Exception: Higher than Boron (B) because Be has a completely filled, stable 2s subshell, making it harder to remove an electron.",
    summary: "Beryllium is a chemical element with symbol Be and atomic number 4. It is created through stellar nucleosynthesis and is a relatively rare element in the universe. It is a divalent element which occurs naturally only in combination with other elements in minerals."
  },
  "B": {
    name: "Boron",
    category: "metalloid",
    block: "p",
    electronConfiguration: "1s2 2s2 2p1",
    valenceConfig: "[He] 2s2 2p1",
    electronegativity: 2.04,
    atomicRadius: 87,
    ionizationEnergy: 800.6,
    electronAffinity: 26.989,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2349,
    boilingPoint: 4200,
    density: 2.08,
    discoverer: "Joseph Louis Gay-Lussac",
    exception: "Ionization Energy Exception: Lower than Beryllium (Be) because its outermost electron is entirely in the higher-energy 2p subshell, making it easier to remove.",
    summary: "Boron is a metalloid chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in both the Solar system and the Earth's crust. Boron is concentrated on Earth by the water-solubility of its more common naturally occurring compounds, the borate minerals."
  },
  "C": {
    name: "Carbon",
    category: "polyatomic nonmetal",
    block: "p",
    electronConfiguration: "1s2 2s2 2p2",
    valenceConfig: "[He] 2s2 2p2",
    electronegativity: 2.55,
    atomicRadius: 67,
    ionizationEnergy: 1086.5,
    electronAffinity: 121.7763,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: null,
    boilingPoint: null,
    density: 1.821,
    discoverer: "Ancient Egypt",
    summary: "Carbon (from Latin:carbo \"coal\") is a chemical element with symbol C and atomic number 6. On the periodic table, it is the first (row 2) of six elements in column (group) 14, which have in common the composition of their outer electron shell. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds."
  },
  "N": {
    name: "Nitrogen",
    category: "diatomic nonmetal",
    block: "p",
    electronConfiguration: "1s2 2s2 2p3",
    valenceConfig: "[He] 2s2 2p3",
    electronegativity: 3.04,
    atomicRadius: 56,
    ionizationEnergy: 1402.3,
    electronAffinity: -6.8,
    oxidationStates: "",
    phase: "Gas",
    meltingPoint: 63.15,
    boilingPoint: 77.355,
    density: 1.251,
    discoverer: "Daniel Rutherford",
    exception: "Ionization Energy Exception: Higher than Oxygen (O) because Nitrogen has an exactly half-filled 2p subshell (2p3), granting it extra stability.",
    summary: "Nitrogen is a chemical element with symbol N and atomic number 7. It is the lightest pnictogen and at room temperature, it is a transparent, odorless diatomic gas. Nitrogen is a common element in the universe, estimated at about seventh in total abundance in the Milky Way and the Solar System."
  },
  "O": {
    name: "Oxygen",
    category: "diatomic nonmetal",
    block: "p",
    electronConfiguration: "1s2 2s2 2p4",
    valenceConfig: "[He] 2s2 2p4",
    electronegativity: 3.44,
    atomicRadius: 48,
    ionizationEnergy: 1313.9,
    electronAffinity: 140.976,
    oxidationStates: "",
    phase: "Gas",
    meltingPoint: 54.36,
    boilingPoint: 90.188,
    density: 1.429,
    discoverer: "Carl Wilhelm Scheele",
    exception: "Ionization Energy Exception: Lower than Nitrogen (N) because removing one paired electron from the 2p subshell relieves inter-electron repulsion.",
    summary: "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table and is a highly reactive nonmetal and oxidizing agent that readily forms compounds (notably oxides) with most elements. By mass, oxygen is the third-most abundant element in the universe, after hydrogen and helium."
  },
  "F": {
    name: "Fluorine",
    category: "diatomic nonmetal",
    block: "p",
    electronConfiguration: "1s2 2s2 2p5",
    valenceConfig: "[He] 2s2 2p5",
    electronegativity: 3.98,
    atomicRadius: 42,
    ionizationEnergy: 1681,
    electronAffinity: 328.1649,
    oxidationStates: "",
    phase: "Gas",
    meltingPoint: 53.48,
    boilingPoint: 85.03,
    density: 1.696,
    discoverer: "André-Marie Ampère",
    exception: "Electron Affinity Exception: Lower affinity (less energy released) than Chlorine (Cl) because Fluorine's extremely small size causes high electron repulsion.",
    summary: "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions. As the most electronegative element, it is extremely reactive:almost all other elements, including some noble gases, form compounds with fluorine."
  },
  "Ne": {
    name: "Neon",
    category: "noble gas",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6",
    valenceConfig: "[Ne]",
    electronegativity: null,
    atomicRadius: 38,
    ionizationEnergy: 2080.7,
    electronAffinity: -116,
    oxidationStates: "",
    phase: "Gas",
    meltingPoint: 24.56,
    boilingPoint: 27.104,
    density: 0.9002,
    discoverer: "Morris Travers",
    summary: "Neon is a chemical element with symbol Ne and atomic number 10. It is in group 18 (noble gases) of the periodic table. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air."
  },
  "Na": {
    name: "Sodium",
    category: "alkali metal",
    block: "s",
    electronConfiguration: "1s2 2s2 2p6 3s1",
    valenceConfig: "[Ne] 3s1",
    electronegativity: 0.93,
    atomicRadius: 190,
    ionizationEnergy: 495.8,
    electronAffinity: 52.867,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 370.944,
    boilingPoint: 1156.09,
    density: 0.968,
    discoverer: "Humphry Davy",
    summary: "Sodium /ˈsoʊdiəm/ is a chemical element with symbol Na (from Ancient Greek Νάτριο) and atomic number 11. It is a soft, silver-white, highly reactive metal. In the Periodic table it is in column 1 (alkali metals), and shares with the other six elements in that column that it has a single electron in its outer shell, which it readily donates, creating a positively charged atom - a cation."
  },
  "Mg": {
    name: "Magnesium",
    category: "alkaline earth metal",
    block: "s",
    electronConfiguration: "1s2 2s2 2p6 3s2",
    valenceConfig: "[Ne] 3s2",
    electronegativity: 1.31,
    atomicRadius: 145,
    ionizationEnergy: 737.7,
    electronAffinity: -40,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 923,
    boilingPoint: 1363,
    density: 1.738,
    discoverer: "Joseph Black",
    exception: "Ionization Energy Exception: Higher than Aluminum (Al) because Mg has a stable, fully-filled 3s subshell.",
    summary: "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column (Group 2, or alkaline earth metals) of the periodic table:they each have the same electron configuration in their outer electron shell producing a similar crystal structure. Magnesium is the ninth most abundant element in the universe."
  },
  "Al": {
    name: "Aluminium",
    category: "post-transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p1",
    valenceConfig: "[Ne] 3s2 3p1",
    electronegativity: 1.61,
    atomicRadius: 118,
    ionizationEnergy: 577.5,
    electronAffinity: 41.762,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 933.47,
    boilingPoint: 2743,
    density: 2.7,
    discoverer: "Unknown",
    exception: "Ionization Energy Exception: Lower than Magnesium (Mg) as it's easier to remove the single 3p electron.",
    summary: "Aluminium (or aluminum; see different endings) is a chemical element in the boron group with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic, ductile metal. Aluminium is the third most abundant element (after oxygen and silicon), and the most abundant metal, in the Earth's crust."
  },
  "Si": {
    name: "Silicon",
    category: "metalloid",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p2",
    valenceConfig: "[Ne] 3s2 3p2",
    electronegativity: 1.9,
    atomicRadius: 111,
    ionizationEnergy: 786.5,
    electronAffinity: 134.0684,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1687,
    boilingPoint: 3538,
    density: 2.329,
    discoverer: "Jöns Jacob Berzelius",
    summary: "Silicon is a chemical element with symbol Si and atomic number 14. It is a tetravalent metalloid, more reactive than germanium, the metalloid directly below it in the table. Controversy about silicon's character dates to its discovery."
  },
  "P": {
    name: "Phosphorus",
    category: "polyatomic nonmetal",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p3",
    valenceConfig: "[Ne] 3s2 3p3",
    electronegativity: 2.19,
    atomicRadius: 98,
    ionizationEnergy: 1011.8,
    electronAffinity: 72.037,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: null,
    boilingPoint: null,
    density: 1.823,
    discoverer: "Hennig Brand",
    exception: "Ionization Energy Exception: Higher than Sulfur (S) because Phosphorus has a stable, half-filled 3p subshell (3p3).",
    summary: "Phosphorus is a chemical element with symbol P and atomic number 15. As an element, phosphorus exists in two major forms—white phosphorus and red phosphorus—but due to its high reactivity, phosphorus is never found as a free element on Earth. Instead phosphorus-containing minerals are almost always present in their maximally oxidised state, as inorganic phosphate rocks."
  },
  "S": {
    name: "Sulfur",
    category: "polyatomic nonmetal",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p4",
    valenceConfig: "[Ne] 3s2 3p4",
    electronegativity: 2.58,
    atomicRadius: 88,
    ionizationEnergy: 999.6,
    electronAffinity: 200.4101,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 388.36,
    boilingPoint: 717.8,
    density: 2.07,
    discoverer: "Ancient china",
    exception: "Ionization Energy Exception: Lower than Phosphorus (P) due to electron-electron repulsion of the paired electrons in the 3p orbital.",
    summary: "Sulfur or sulphur (see spelling differences) is a chemical element with symbol S and atomic number 16. It is an abundant, multivalent non-metal. Under normal conditions, sulfur atoms form cyclic octatomic molecules with chemical formula S8."
  },
  "Cl": {
    name: "Chlorine",
    category: "diatomic nonmetal",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p5",
    valenceConfig: "[Ne] 3s2 3p5",
    electronegativity: 3.16,
    atomicRadius: 79,
    ionizationEnergy: 1251.2,
    electronAffinity: 348.575,
    oxidationStates: "",
    phase: "Gas",
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    density: 3.2,
    discoverer: "Carl Wilhelm Scheele",
    exception: "Electron Affinity Exception: Higher affinity than Fluorine (F). Though lower in the group, its larger 3p orbital has less electron repulsion.",
    summary: "Chlorine is a chemical element with symbol Cl and atomic number 17. It also has a relative atomic mass of 35.5. Chlorine is in the halogen group (17) and is the second lightest halogen following fluorine."
  },
  "Ar": {
    name: "Argon",
    category: "noble gas",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6",
    valenceConfig: "[Ar]",
    electronegativity: null,
    atomicRadius: 71,
    ionizationEnergy: 1520.6,
    electronAffinity: -96,
    oxidationStates: "",
    phase: "Gas",
    meltingPoint: 83.81,
    boilingPoint: 87.302,
    density: 1.784,
    discoverer: "Lord Rayleigh",
    summary: "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third most common gas in the Earth's atmosphere, at 0.934% (9,340 ppmv), making it over twice as abundant as the next most common atmospheric gas, water vapor (which averages about 4000 ppmv, but varies greatly), and 23 times as abundant as the next most common non-condensing atmospheric gas, carbon dioxide (400 ppmv), and more than 500 times as abundant as the next most common noble gas, neon (18 ppmv)."
  },
  "K": {
    name: "Potassium",
    category: "alkali metal",
    block: "s",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s1",
    valenceConfig: "[Ar] 4s1",
    electronegativity: 0.82,
    atomicRadius: 243,
    ionizationEnergy: 418.8,
    electronAffinity: 48.383,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 336.7,
    boilingPoint: 1032,
    density: 0.862,
    discoverer: "Humphry Davy",
    summary: "Potassium is a chemical element with symbol K (derived from Neo-Latin, kalium) and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name is derived. In the Periodic table, potassium is one of seven elements in column (group) 1 (alkali metals):they all have a single valence electron in their outer electron shell, which they readily give up to create an atom with a positive charge - a cation, and combine with anions to form salts."
  },
  "Ca": {
    name: "Calcium",
    category: "alkaline earth metal",
    block: "s",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2",
    valenceConfig: "[Ar] 4s2",
    electronegativity: 1,
    atomicRadius: 194,
    ionizationEnergy: 589.8,
    electronAffinity: 2.37,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1115,
    boilingPoint: 1757,
    density: 1.55,
    discoverer: "Humphry Davy",
    summary: "Calcium is a chemical element with symbol Ca and atomic number 20. Calcium is a soft gray alkaline earth metal, fifth-most-abundant element by mass in the Earth's crust. The ion Ca2+ is also the fifth-most-abundant dissolved ion in seawater by both molarity and mass, after sodium, chloride, magnesium, and sulfate."
  },
  "Sc": {
    name: "Scandium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d1",
    valenceConfig: "[Ar] 4s2 3d1",
    electronegativity: 1.36,
    atomicRadius: 184,
    ionizationEnergy: 633.1,
    electronAffinity: 18,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1814,
    boilingPoint: 3109,
    density: 2.985,
    discoverer: "Lars Fredrik Nilson",
    summary: "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been sometimes classified as a rare earth element, together with yttrium and the lanthanoids. It was discovered in 1879 by spectral analysis of the minerals euxenite and gadolinite from Scandinavia."
  },
  "Ti": {
    name: "Titanium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d2",
    valenceConfig: "[Ar] 4s2 3d2",
    electronegativity: 1.54,
    atomicRadius: 176,
    ionizationEnergy: 658.8,
    electronAffinity: 7.289,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1941,
    boilingPoint: 3560,
    density: 4.506,
    discoverer: "William Gregor",
    summary: "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density and high strength. It is highly resistant to corrosion in sea water, aqua regia and chlorine."
  },
  "V": {
    name: "Vanadium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d3",
    valenceConfig: "[Ar] 4s2 3d3",
    electronegativity: 1.63,
    atomicRadius: 171,
    ionizationEnergy: 650.9,
    electronAffinity: 50.911,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2183,
    boilingPoint: 3680,
    density: 6,
    discoverer: "Andrés Manuel del Río",
    summary: "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery grey, ductile and malleable transition metal. The element is found only in chemically combined form in nature, but once isolated artificially, the formation of an oxide layer stabilizes the free metal somewhat against further oxidation."
  },
  "Cr": {
    name: "Chromium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s1 3d5",
    valenceConfig: "[Ar] 4s1 3d5",
    electronegativity: 1.66,
    atomicRadius: 166,
    ionizationEnergy: 652.9,
    electronAffinity: 65.21,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2180,
    boilingPoint: 2944,
    density: 7.19,
    discoverer: "Louis Nicolas Vauquelin",
    exception: "Electron Configuration Exception: Moves an s-electron to the d-orbital ([Ar] 4s1 3d5) to attain a more stable, half-filled 3d subshell.",
    summary: "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in Group 6. It is a steely-gray, lustrous, hard and brittle metal which takes a high polish, resists tarnishing, and has a high melting point."
  },
  "Mn": {
    name: "Manganese",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d5",
    valenceConfig: "[Ar] 4s2 3d5",
    electronegativity: 1.55,
    atomicRadius: 161,
    ionizationEnergy: 717.3,
    electronAffinity: -50,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1519,
    boilingPoint: 2334,
    density: 7.21,
    discoverer: "Torbern Olof Bergman",
    summary: "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in combination with iron, and in many minerals. Manganese is a metal with important industrial metal alloy uses, particularly in stainless steels."
  },
  "Fe": {
    name: "Iron",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d6",
    valenceConfig: "[Ar] 4s2 3d6",
    electronegativity: 1.83,
    atomicRadius: 156,
    ionizationEnergy: 762.5,
    electronAffinity: 14.785,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1811,
    boilingPoint: 3134,
    density: 7.874,
    discoverer: "5000 BC",
    summary: "Iron is a chemical element with symbol Fe (from Latin:ferrum) and atomic number 26. It is a metal in the first transition series. It is by mass the most common element on Earth, forming much of Earth's outer and inner core."
  },
  "Co": {
    name: "Cobalt",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d7",
    valenceConfig: "[Ar] 4s2 3d7",
    electronegativity: 1.88,
    atomicRadius: 152,
    ionizationEnergy: 760.4,
    electronAffinity: 63.898,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1768,
    boilingPoint: 3200,
    density: 8.9,
    discoverer: "Georg Brandt",
    summary: "Cobalt is a chemical element with symbol Co and atomic number 27. Like nickel, cobalt in the Earth's crust is found only in chemically combined form, save for small deposits found in alloys of natural meteoric iron. The free element, produced by reductive smelting, is a hard, lustrous, silver-gray metal."
  },
  "Ni": {
    name: "Nickel",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d8",
    valenceConfig: "[Ar] 4s2 3d8",
    electronegativity: 1.91,
    atomicRadius: 149,
    ionizationEnergy: 737.1,
    electronAffinity: 111.65,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1728,
    boilingPoint: 3003,
    density: 8.908,
    discoverer: "Axel Fredrik Cronstedt",
    summary: "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge. Nickel belongs to the transition metals and is hard and ductile."
  },
  "Cu": {
    name: "Copper",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s1 3d10",
    valenceConfig: "[Ar] 4s1 3d10",
    electronegativity: 1.9,
    atomicRadius: 145,
    ionizationEnergy: 745.5,
    electronAffinity: 119.235,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    density: 8.96,
    discoverer: "Middle East",
    exception: "Electron Configuration Exception: Moves an s-electron to the d-orbital ([Ar] 4s1 3d10) to attain a more stable, completely filled 3d subshell.",
    summary: "Copper is a chemical element with symbol Cu (from Latin:cuprum) and atomic number 29. It is a soft, malleable and ductile metal with very high thermal and electrical conductivity. A freshly exposed surface of pure copper has a reddish-orange color."
  },
  "Zn": {
    name: "Zinc",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10",
    valenceConfig: "[Ar] 4s2 3d10",
    electronegativity: 1.65,
    atomicRadius: 142,
    ionizationEnergy: 906.4,
    electronAffinity: -58,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 692.68,
    boilingPoint: 1180,
    density: 7.14,
    discoverer: "India",
    summary: "Zinc, in commerce also spelter, is a chemical element with symbol Zn and atomic number 30. It is the first element of group 12 of the periodic table. In some respects zinc is chemically similar to magnesium:its ion is of similar size and its only common oxidation state is +2."
  },
  "Ga": {
    name: "Gallium",
    category: "post-transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p1",
    valenceConfig: "[Ar] 4s2 3d10 4p1",
    electronegativity: 1.81,
    atomicRadius: 136,
    ionizationEnergy: 578.8,
    electronAffinity: 41,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 302.9146,
    boilingPoint: 2673,
    density: 5.91,
    discoverer: "Lecoq de Boisbaudran",
    exception: "Atomic Radius Exception: Smaller or remarkably similar in size to Aluminum (Al) above it due to 'd-block contraction' (poor shielding of the 3d electrons).",
    summary: "Gallium is a chemical element with symbol Ga and atomic number 31. Elemental gallium does not occur in free form in nature, but as the gallium(III) compounds that are in trace amounts in zinc ores and in bauxite. Gallium is a soft, silvery metal, and elemental gallium is a brittle solid at low temperatures, and melts at 29.76 °C (85.57 °F) (slightly above room temperature)."
  },
  "Ge": {
    name: "Germanium",
    category: "metalloid",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p2",
    valenceConfig: "[Ar] 4s2 3d10 4p2",
    electronegativity: 2.01,
    atomicRadius: 125,
    ionizationEnergy: 762,
    electronAffinity: 118.9352,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1211.4,
    boilingPoint: 3106,
    density: 5.323,
    discoverer: "Clemens Winkler",
    summary: "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard, grayish-white metalloid in the carbon group, chemically similar to its group neighbors tin and silicon. Purified germanium is a semiconductor, with an appearance most similar to elemental silicon."
  },
  "As": {
    name: "Arsenic",
    category: "metalloid",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p3",
    valenceConfig: "[Ar] 4s2 3d10 4p3",
    electronegativity: 2.18,
    atomicRadius: 114,
    ionizationEnergy: 947,
    electronAffinity: 77.65,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: null,
    boilingPoint: null,
    density: 5.727,
    discoverer: "Bronze Age",
    summary: "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in conjunction with sulfur and metals, and also as a pure elemental crystal. Arsenic is a metalloid."
  },
  "Se": {
    name: "Selenium",
    category: "polyatomic nonmetal",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p4",
    valenceConfig: "[Ar] 4s2 3d10 4p4",
    electronegativity: 2.55,
    atomicRadius: 103,
    ionizationEnergy: 941,
    electronAffinity: 194.9587,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 494,
    boilingPoint: 958,
    density: 4.81,
    discoverer: "Jöns Jakob Berzelius",
    summary: "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between those of its periodic table column-adjacent chalcogen elements sulfur and tellurium. It rarely occurs in its elemental state in nature, or as pure ore compounds."
  },
  "Br": {
    name: "Bromine",
    category: "diatomic nonmetal",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p5",
    valenceConfig: "[Ar] 4s2 3d10 4p5",
    electronegativity: 2.96,
    atomicRadius: 94,
    ionizationEnergy: 1139.9,
    electronAffinity: 324.537,
    oxidationStates: "",
    phase: "Liquid",
    meltingPoint: 265.8,
    boilingPoint: 332,
    density: 3.1028,
    discoverer: "Antoine Jérôme Balard",
    summary: "Bromine (from Ancient Greek:βρῶμος, brómos, meaning \"stench\") is a chemical element with symbol Br, and atomic number 35. It is a halogen. The element was isolated independently by two chemists, Carl Jacob Löwig and Antoine Jerome Balard, in 1825–1826."
  },
  "Kr": {
    name: "Krypton",
    category: "noble gas",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6",
    valenceConfig: "[Kr]",
    electronegativity: 3,
    atomicRadius: 88,
    ionizationEnergy: 1350.8,
    electronAffinity: -96,
    oxidationStates: "",
    phase: "Gas",
    meltingPoint: 115.78,
    boilingPoint: 119.93,
    density: 3.749,
    discoverer: "William Ramsay",
    summary: "Krypton (from Greek:κρυπτός kryptos \"the hidden one\") is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements. A colorless, odorless, tasteless noble gas, krypton occurs in trace amounts in the atmosphere, is isolated by fractionally distilling liquefied air, and is often used with other rare gases in fluorescent lamps."
  },
  "Rb": {
    name: "Rubidium",
    category: "alkali metal",
    block: "s",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1",
    valenceConfig: "[Kr] 5s1",
    electronegativity: 0.82,
    atomicRadius: 265,
    ionizationEnergy: 403,
    electronAffinity: 46.884,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 312.45,
    boilingPoint: 961,
    density: 1.532,
    discoverer: "Robert Bunsen",
    summary: "Rubidium is a chemical element with symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group, with an atomic mass of 85.4678. Elemental rubidium is highly reactive, with properties similar to those of other alkali metals, such as very rapid oxidation in air."
  },
  "Sr": {
    name: "Strontium",
    category: "alkaline earth metal",
    block: "s",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2",
    valenceConfig: "[Kr] 5s2",
    electronegativity: 0.95,
    atomicRadius: 219,
    ionizationEnergy: 549.5,
    electronAffinity: 5.023,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1050,
    boilingPoint: 1650,
    density: 2.64,
    discoverer: "William Cruickshank (chemist)",
    summary: "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white or yellowish metallic element that is highly reactive chemically. The metal turns yellow when it is exposed to air."
  },
  "Y": {
    name: "Yttrium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d1",
    valenceConfig: "[Kr] 5s2 4d1",
    electronegativity: 1.22,
    atomicRadius: 212,
    ionizationEnergy: 600,
    electronAffinity: 29.6,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1799,
    boilingPoint: 3203,
    density: 4.472,
    discoverer: "Johan Gadolin",
    summary: "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides and it has often been classified as a \"rare earth element\". Yttrium is almost always found combined with the lanthanides in rare earth minerals and is never found in nature as a free element."
  },
  "Zr": {
    name: "Zirconium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d2",
    valenceConfig: "[Kr] 5s2 4d2",
    electronegativity: 1.33,
    atomicRadius: 206,
    ionizationEnergy: 640.1,
    electronAffinity: 41.806,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2128,
    boilingPoint: 4650,
    density: 6.52,
    discoverer: "Martin Heinrich Klaproth",
    summary: "Zirconium is a chemical element with symbol Zr and atomic number 40. The name of zirconium is taken from the name of the mineral zircon, the most important source of zirconium. The word zircon comes from the Persian word zargun زرگون, meaning \"gold-colored\"."
  },
  "Nb": {
    name: "Niobium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d4",
    valenceConfig: "[Kr] 5s1 4d4",
    electronegativity: 1.6,
    atomicRadius: 198,
    ionizationEnergy: 652.1,
    electronAffinity: 88.516,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2750,
    boilingPoint: 5017,
    density: 8.57,
    discoverer: "Charles Hatchett",
    summary: "Niobium, formerly columbium, is a chemical element with symbol Nb (formerly Cb) and atomic number 41. It is a soft, grey, ductile transition metal, which is often found in the pyrochlore mineral, the main commercial source for niobium, and columbite. The name comes from Greek mythology:Niobe, daughter of Tantalus since it is so similar to tantalum."
  },
  "Mo": {
    name: "Molybdenum",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d5",
    valenceConfig: "[Kr] 5s1 4d5",
    electronegativity: 2.16,
    atomicRadius: 190,
    ionizationEnergy: 684.3,
    electronAffinity: 72.1,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2896,
    boilingPoint: 4912,
    density: 10.28,
    discoverer: "Carl Wilhelm Scheele",
    exception: "Electron Configuration Exception: Similar to Chromium, it assumes a [Kr] 5s1 4d5 configuration for a stable half-filled d-subshell.",
    summary: "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin molybdaenum, from Ancient Greek Μόλυβδος molybdos, meaning lead, since its ores were confused with lead ores. Molybdenum minerals have been known throughout history, but the element was discovered (in the sense of differentiating it as a new entity from the mineral salts of other metals) in 1778 by Carl Wilhelm Scheele."
  },
  "Tc": {
    name: "Technetium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d5",
    valenceConfig: "[Kr] 5s2 4d5",
    electronegativity: 1.9,
    atomicRadius: 183,
    ionizationEnergy: 702,
    electronAffinity: 53,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2430,
    boilingPoint: 4538,
    density: 11,
    discoverer: "Emilio Segrè",
    summary: "Technetium (/tɛkˈniːʃiəm/) is a chemical element with symbol Tc and atomic number 43. It is the element with the lowest atomic number in the periodic table that has no stable isotopes:every form of it is radioactive. Nearly all technetium is produced synthetically, and only minute amounts are found in nature."
  },
  "Ru": {
    name: "Ruthenium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d7",
    valenceConfig: "[Kr] 5s1 4d7",
    electronegativity: 2.2,
    atomicRadius: 178,
    ionizationEnergy: 710.2,
    electronAffinity: 100.96,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2607,
    boilingPoint: 4423,
    density: 12.45,
    discoverer: "Karl Ernst Claus",
    summary: "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table. Like the other metals of the platinum group, ruthenium is inert to most other chemicals."
  },
  "Rh": {
    name: "Rhodium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d8",
    valenceConfig: "[Kr] 5s1 4d8",
    electronegativity: 2.28,
    atomicRadius: 173,
    ionizationEnergy: 719.7,
    electronAffinity: 110.27,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2237,
    boilingPoint: 3968,
    density: 12.41,
    discoverer: "William Hyde Wollaston",
    summary: "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, and chemically inert transition metal. It is a member of the platinum group."
  },
  "Pd": {
    name: "Palladium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 4d10",
    valenceConfig: "[Kr] 4d10",
    electronegativity: 2.2,
    atomicRadius: 169,
    ionizationEnergy: 804.4,
    electronAffinity: 54.24,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1828.05,
    boilingPoint: 3236,
    density: 12.023,
    discoverer: "William Hyde Wollaston",
    exception: "Electron Configuration Exception: Very anomalous! It transfers both s-electrons to the d-subshell, resulting in a unique [Kr] 4d10 configuration with an empty outermost s-shell.",
    summary: "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803 by William Hyde Wollaston. He named it after the asteroid Pallas, which was itself named after the epithet of the Greek goddess Athena, acquired by her when she slew Pallas."
  },
  "Ag": {
    name: "Silver",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s1 4d10",
    valenceConfig: "[Kr] 5s1 4d10",
    electronegativity: 1.93,
    atomicRadius: 165,
    ionizationEnergy: 731,
    electronAffinity: 125.862,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1234.93,
    boilingPoint: 2435,
    density: 10.49,
    discoverer: "unknown, before 5000 BC",
    exception: "Electron Configuration Exception: Similar to Copper, it assumes a [Kr] 5s1 4d10 configuration to completely fill its d-subshell.",
    summary: "Silver is a chemical element with symbol Ag (Greek:άργυρος árguros, Latin:argentum, both from the Indo-European root *h₂erǵ- for \"grey\" or \"shining\") and atomic number 47. A soft, white, lustrous transition metal, it possesses the highest electrical conductivity, thermal conductivity and reflectivity of any metal. The metal occurs naturally in its pure, free form (native silver), as an alloy with gold and other metals, and in minerals such as argentite and chlorargyrite."
  },
  "Cd": {
    name: "Cadmium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10",
    valenceConfig: "[Kr] 5s2 4d10",
    electronegativity: 1.69,
    atomicRadius: 161,
    ionizationEnergy: 867.8,
    electronAffinity: -68,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 594.22,
    boilingPoint: 1040,
    density: 8.65,
    discoverer: "Karl Samuel Leberecht Hermann",
    summary: "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, bluish-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury. Like zinc, it prefers oxidation state +2 in most of its compounds and like mercury it shows a low melting point compared to transition metals."
  },
  "In": {
    name: "Indium",
    category: "post-transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p1",
    valenceConfig: "[Kr] 5s2 4d10 5p1",
    electronegativity: 1.78,
    atomicRadius: 156,
    ionizationEnergy: 558.3,
    electronAffinity: 37.043,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 429.7485,
    boilingPoint: 2345,
    density: 7.31,
    discoverer: "Ferdinand Reich",
    summary: "Indium is a chemical element with symbol In and atomic number 49. It is a post-transition metallic element that is rare in Earth's crust. The metal is very soft, malleable and easily fusible, with a melting point higher than sodium, but lower than lithium or tin."
  },
  "Sn": {
    name: "Tin",
    category: "post-transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p2",
    valenceConfig: "[Kr] 5s2 4d10 5p2",
    electronegativity: 1.96,
    atomicRadius: 145,
    ionizationEnergy: 708.6,
    electronAffinity: 107.2984,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 505.08,
    boilingPoint: 2875,
    density: 7.365,
    discoverer: "unknown, before 3500 BC",
    summary: "Tin is a chemical element with the symbol Sn (for Latin:stannum) and atomic number 50. It is a main group metal in group 14 of the periodic table. Tin shows a chemical similarity to both neighboring group-14 elements, germanium and lead, and has two possible oxidation states, +2 and the slightly more stable +4."
  },
  "Sb": {
    name: "Antimony",
    category: "metalloid",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p3",
    valenceConfig: "[Kr] 5s2 4d10 5p3",
    electronegativity: 2.05,
    atomicRadius: 133,
    ionizationEnergy: 834,
    electronAffinity: 101.059,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 903.78,
    boilingPoint: 1908,
    density: 6.697,
    discoverer: "unknown, before 3000 BC",
    summary: "Antimony is a chemical element with symbol Sb (from Latin:stibium) and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite (Sb2S3). Antimony compounds have been known since ancient times and were used for cosmetics; metallic antimony was also known, but it was erroneously identified as lead upon its discovery."
  },
  "Te": {
    name: "Tellurium",
    category: "metalloid",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p4",
    valenceConfig: "[Kr] 5s2 4d10 5p4",
    electronegativity: 2.1,
    atomicRadius: 123,
    ionizationEnergy: 869.3,
    electronAffinity: 190.161,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 722.66,
    boilingPoint: 1261,
    density: 6.24,
    discoverer: "Franz-Joseph Müller von Reichenstein",
    summary: "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid. Tellurium is chemically related to selenium and sulfur."
  },
  "I": {
    name: "Iodine",
    category: "diatomic nonmetal",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p5",
    valenceConfig: "[Kr] 5s2 4d10 5p5",
    electronegativity: 2.66,
    atomicRadius: 115,
    ionizationEnergy: 1008.4,
    electronAffinity: 295.1531,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 386.85,
    boilingPoint: 457.4,
    density: 4.933,
    discoverer: "Bernard Courtois",
    summary: "Iodine is a chemical element with symbol I and atomic number 53. The name is from Greek ἰοειδής ioeidēs, meaning violet or purple, due to the color of iodine vapor. Iodine and its compounds are primarily used in nutrition, and industrially in the production of acetic acid and certain polymers."
  },
  "Xe": {
    name: "Xenon",
    category: "noble gas",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6",
    valenceConfig: "[Xe]",
    electronegativity: 2.6,
    atomicRadius: 108,
    ionizationEnergy: 1170.4,
    electronAffinity: -77,
    oxidationStates: "",
    phase: "Gas",
    meltingPoint: 161.4,
    boilingPoint: 165.051,
    density: 5.894,
    discoverer: "William Ramsay",
    summary: "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas, that occurs in the Earth's atmosphere in trace amounts. Although generally unreactive, xenon can undergo a few chemical reactions such as the formation of xenon hexafluoroplatinate, the first noble gas compound to be synthesized."
  },
  "Cs": {
    name: "Cesium",
    category: "alkali metal",
    block: "s",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s1",
    valenceConfig: "[Xe] 6s1",
    electronegativity: 0.79,
    atomicRadius: 298,
    ionizationEnergy: 375.7,
    electronAffinity: 45.505,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 301.7,
    boilingPoint: 944,
    density: 1.93,
    discoverer: "Robert Bunsen",
    summary: "Caesium or cesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-gold alkali metal with a melting point of 28 °C (82 °F), which makes it one of only five elemental metals that are liquid at or near room temperature. Caesium is an alkali metal and has physical and chemical properties similar to those of rubidium and potassium."
  },
  "Ba": {
    name: "Barium",
    category: "alkaline earth metal",
    block: "s",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2",
    valenceConfig: "[Xe] 6s2",
    electronegativity: 0.89,
    atomicRadius: 253,
    ionizationEnergy: 502.9,
    electronAffinity: 13.954,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1000,
    boilingPoint: 2118,
    density: 3.51,
    discoverer: "Carl Wilhelm Scheele",
    summary: "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in Group 2, a soft silvery metallic alkaline earth metal. Because of its high chemical reactivity barium is never found in nature as a free element."
  },
  "La": {
    name: "Lanthanum",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 5d1",
    valenceConfig: "[Xe] 6s2 5d1",
    electronegativity: 1.1,
    atomicRadius: 195,
    ionizationEnergy: 538.1,
    electronAffinity: 53,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1193,
    boilingPoint: 3737,
    density: 6.162,
    discoverer: "Carl Gustaf Mosander",
    summary: "Lanthanum is a soft, ductile, silvery-white metallic chemical element with symbol La and atomic number 57. It tarnishes rapidly when exposed to air and is soft enough to be cut with a knife. It gave its name to the lanthanide series, a group of 15 similar elements between lanthanum and lutetium in the periodic table:it is also sometimes considered the first element of the 6th-period transition metals."
  },
  "Ce": {
    name: "Cerium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 5d1 4f1",
    valenceConfig: "[Xe] 6s2 5d1 4f1",
    electronegativity: 1.12,
    atomicRadius: 185,
    ionizationEnergy: 534.4,
    electronAffinity: 55,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1068,
    boilingPoint: 3716,
    density: 6.77,
    discoverer: "Martin Heinrich Klaproth",
    summary: "Cerium is a chemical element with symbol Ce and atomic number 58. It is a soft, silvery, ductile metal which easily oxidizes in air. Cerium was named after the dwarf planet Ceres (itself named after the Roman goddess of agriculture)."
  },
  "Pr": {
    name: "Praseodymium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f3",
    valenceConfig: "[Xe] 6s2 4f3",
    electronegativity: 1.13,
    atomicRadius: 185,
    ionizationEnergy: 527,
    electronAffinity: 93,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1208,
    boilingPoint: 3403,
    density: 6.77,
    discoverer: "Carl Auer von Welsbach",
    summary: "Praseodymium is a chemical element with symbol Pr and atomic number 59. Praseodymium is a soft, silvery, malleable and ductile metal in the lanthanide group. It is valued for its magnetic, electrical, chemical, and optical properties."
  },
  "Nd": {
    name: "Neodymium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f4",
    valenceConfig: "[Xe] 6s2 4f4",
    electronegativity: 1.14,
    atomicRadius: 185,
    ionizationEnergy: 533.1,
    electronAffinity: 184.87,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1297,
    boilingPoint: 3347,
    density: 7.01,
    discoverer: "Carl Auer von Welsbach",
    summary: "Neodymium is a chemical element with symbol Nd and atomic number 60. It is a soft silvery metal that tarnishes in air. Neodymium was discovered in 1885 by the Austrian chemist Carl Auer von Welsbach."
  },
  "Pm": {
    name: "Promethium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f5",
    valenceConfig: "[Xe] 6s2 4f5",
    electronegativity: 1.13,
    atomicRadius: 185,
    ionizationEnergy: 540,
    electronAffinity: 12.45,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1315,
    boilingPoint: 3273,
    density: 7.26,
    discoverer: "Chien Shiung Wu",
    summary: "Promethium, originally prometheum, is a chemical element with the symbol Pm and atomic number 61. All of its isotopes are radioactive; it is one of only two such elements that are followed in the periodic table by elements with stable forms, a distinction shared with technetium. Chemically, promethium is a lanthanide, which forms salts when combined with other elements."
  },
  "Sm": {
    name: "Samarium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f6",
    valenceConfig: "[Xe] 6s2 4f6",
    electronegativity: 1.17,
    atomicRadius: 185,
    ionizationEnergy: 544.5,
    electronAffinity: 15.63,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1345,
    boilingPoint: 2173,
    density: 7.52,
    discoverer: "Lecoq de Boisbaudran",
    summary: "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that readily oxidizes in air. Being a typical member of the lanthanide series, samarium usually assumes the oxidation state +3."
  },
  "Eu": {
    name: "Europium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f7",
    valenceConfig: "[Xe] 6s2 4f7",
    electronegativity: 1.2,
    atomicRadius: 185,
    ionizationEnergy: 547.1,
    electronAffinity: 11.2,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1099,
    boilingPoint: 1802,
    density: 5.264,
    discoverer: "Eugène-Anatole Demarçay",
    summary: "Europium is a chemical element with symbol Eu and atomic number 63. It was isolated in 1901 and is named after the continent of Europe. It is a moderately hard, silvery metal which readily oxidizes in air and water."
  },
  "Gd": {
    name: "Gadolinium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f7 5d1",
    valenceConfig: "[Xe] 6s2 4f7 5d1",
    electronegativity: 1.2,
    atomicRadius: 180,
    ionizationEnergy: 593.4,
    electronAffinity: 13.22,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1585,
    boilingPoint: 3273,
    density: 7.9,
    discoverer: "Jean Charles Galissard de Marignac",
    summary: "Gadolinium is a chemical element with symbol Gd and atomic number 64. It is a silvery-white, malleable and ductile rare-earth metal. It is found in nature only in combined (salt) form."
  },
  "Tb": {
    name: "Terbium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f9",
    valenceConfig: "[Xe] 6s2 4f9",
    electronegativity: 1.1,
    atomicRadius: 175,
    ionizationEnergy: 565.8,
    electronAffinity: 112.4,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1629,
    boilingPoint: 3396,
    density: 8.23,
    discoverer: "Carl Gustaf Mosander",
    summary: "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white rare earth metal that is malleable, ductile and soft enough to be cut with a knife. Terbium is never found in nature as a free element, but it is contained in many minerals, including cerite, gadolinite, monazite, xenotime and euxenite."
  },
  "Dy": {
    name: "Dysprosium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f10",
    valenceConfig: "[Xe] 6s2 4f10",
    electronegativity: 1.22,
    atomicRadius: 175,
    ionizationEnergy: 573,
    electronAffinity: 33.96,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1680,
    boilingPoint: 2840,
    density: 8.54,
    discoverer: "Lecoq de Boisbaudran",
    summary: "Dysprosium is a chemical element with the symbol Dy and atomic number 66. It is a rare earth element with a metallic silver luster. Dysprosium is never found in nature as a free element, though it is found in various minerals, such as xenotime."
  },
  "Ho": {
    name: "Holmium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f11",
    valenceConfig: "[Xe] 6s2 4f11",
    electronegativity: 1.23,
    atomicRadius: 175,
    ionizationEnergy: 581,
    electronAffinity: 32.61,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1734,
    boilingPoint: 2873,
    density: 8.79,
    discoverer: "Marc Delafontaine",
    summary: "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare earth element. Holmium was discovered by Swedish chemist Per Theodor Cleve."
  },
  "Er": {
    name: "Erbium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f12",
    valenceConfig: "[Xe] 6s2 4f12",
    electronegativity: 1.24,
    atomicRadius: 175,
    ionizationEnergy: 589.3,
    electronAffinity: 30.1,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1802,
    boilingPoint: 3141,
    density: 9.066,
    discoverer: "Carl Gustaf Mosander",
    summary: "Erbium is a chemical element in the lanthanide series, with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements on Earth. As such, it is a rare earth element which is associated with several other rare elements in the mineral gadolinite from Ytterby in Sweden, where yttrium, ytterbium, and terbium were discovered."
  },
  "Tm": {
    name: "Thulium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f13",
    valenceConfig: "[Xe] 6s2 4f13",
    electronegativity: 1.25,
    atomicRadius: 175,
    ionizationEnergy: 596.7,
    electronAffinity: 99,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1818,
    boilingPoint: 2223,
    density: 9.32,
    discoverer: "Per Teodor Cleve",
    summary: "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and antepenultimate (third-last) element in the lanthanide series. Like the other lanthanides, the most common oxidation state is +3, seen in its oxide, halides and other compounds."
  },
  "Yb": {
    name: "Ytterbium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14",
    valenceConfig: "[Xe] 6s2 4f14",
    electronegativity: 1.1,
    atomicRadius: 175,
    ionizationEnergy: 603.4,
    electronAffinity: -1.93,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1097,
    boilingPoint: 1469,
    density: 6.9,
    discoverer: "Jean Charles Galissard de Marignac",
    summary: "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series, which is the basis of the relative stability of its +2 oxidation state. However, like the other lanthanides, its most common oxidation state is +3, seen in its oxide, halides and other compounds."
  },
  "Lu": {
    name: "Lutetium",
    category: "lanthanide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d1",
    valenceConfig: "[Xe] 6s2 4f14 5d1",
    electronegativity: 1.27,
    atomicRadius: 175,
    ionizationEnergy: 523.5,
    electronAffinity: 33.4,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1925,
    boilingPoint: 3675,
    density: 9.841,
    discoverer: "Georges Urbain",
    summary: "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry, but not in moist air. It is considered the first element of the 6th-period transition metals and the last element in the lanthanide series, and is traditionally counted among the rare earths."
  },
  "Hf": {
    name: "Hafnium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d2",
    valenceConfig: "[Xe] 6s2 4f14 5d2",
    electronegativity: 1.3,
    atomicRadius: 208,
    ionizationEnergy: 658.5,
    electronAffinity: 17.18,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2506,
    boilingPoint: 4876,
    density: 13.31,
    discoverer: "Dirk Coster",
    summary: "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in zirconium minerals. Its existence was predicted by Dmitri Mendeleev in 1869, though it was not identified until 1923, making it the penultimate stable element to be discovered (rhenium was identified two years later)."
  },
  "Ta": {
    name: "Tantalum",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d3",
    valenceConfig: "[Xe] 6s2 4f14 5d3",
    electronegativity: 1.5,
    atomicRadius: 200,
    ionizationEnergy: 761,
    electronAffinity: 31,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 3290,
    boilingPoint: 5731,
    density: 16.69,
    discoverer: "Anders Gustaf Ekeberg",
    summary: "Tantalum is a chemical element with symbol Ta and atomic number 73. Previously known as tantalium, its name comes from Tantalus, an antihero from Greek mythology. Tantalum is a rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant."
  },
  "W": {
    name: "Tungsten",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d4",
    valenceConfig: "[Xe] 6s2 4f14 5d4",
    electronegativity: 2.36,
    atomicRadius: 193,
    ionizationEnergy: 770,
    electronAffinity: 78.76,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 3695,
    boilingPoint: 6203,
    density: 19.25,
    discoverer: "Carl Wilhelm Scheele",
    summary: "Tungsten, also known as wolfram, is a chemical element with symbol W and atomic number 74. The word tungsten comes from the Swedish language tung sten, which directly translates to heavy stone. Its name in Swedish is volfram, however, in order to distinguish it from scheelite, which in Swedish is alternatively named tungsten."
  },
  "Re": {
    name: "Rhenium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d5",
    valenceConfig: "[Xe] 6s2 4f14 5d5",
    electronegativity: 1.9,
    atomicRadius: 188,
    ionizationEnergy: 760,
    electronAffinity: 5.8273,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 3459,
    boilingPoint: 5869,
    density: 21.02,
    discoverer: "Masataka Ogawa",
    summary: "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-white, heavy, third-row transition metal in group 7 of the periodic table. With an estimated average concentration of 1 part per billion (ppb), rhenium is one of the rarest elements in the Earth's crust."
  },
  "Os": {
    name: "Osmium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d6",
    valenceConfig: "[Xe] 6s2 4f14 5d6",
    electronegativity: 2.2,
    atomicRadius: 185,
    ionizationEnergy: 840,
    electronAffinity: 103.99,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 3306,
    boilingPoint: 5285,
    density: 22.59,
    discoverer: "Smithson Tennant",
    summary: "Osmium (from Greek osme (ὀσμή) meaning \"smell\") is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores. Osmium is the densest naturally occurring element, with a density of 22.59 g/cm3."
  },
  "Ir": {
    name: "Iridium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d7",
    valenceConfig: "[Xe] 6s2 4f14 5d7",
    electronegativity: 2.2,
    atomicRadius: 180,
    ionizationEnergy: 880,
    electronAffinity: 150.94,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2719,
    boilingPoint: 4403,
    density: 22.56,
    discoverer: "Smithson Tennant",
    summary: "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is generally credited with being the second densest element (after osmium) based on measured density, although calculations involving the space lattices of the elements show that iridium is denser. It is also the most corrosion-resistant metal, even at temperatures as high as 2000 °C. Although only certain molten salts and halogens are corrosive to solid iridium, finely divided iridium dust is much more reactive and can be flammable."
  },
  "Pt": {
    name: "Platinum",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s1 4f14 5d9",
    valenceConfig: "[Xe] 6s1 4f14 5d9",
    electronegativity: 2.28,
    atomicRadius: 177,
    ionizationEnergy: 870,
    electronAffinity: 205.041,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2041.4,
    boilingPoint: 4098,
    density: 21.45,
    discoverer: "Antonio de Ulloa",
    summary: "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, gray-white transition metal. Its name is derived from the Spanish term platina, which is literally translated into \"little silver\"."
  },
  "Au": {
    name: "Gold",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s1 4f14 5d10",
    valenceConfig: "[Xe] 6s1 4f14 5d10",
    electronegativity: 2.54,
    atomicRadius: 174,
    ionizationEnergy: 890.1,
    electronAffinity: 222.747,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1337.33,
    boilingPoint: 3243,
    density: 19.3,
    discoverer: "Middle East",
    summary: "Gold is a chemical element with symbol Au (from Latin:aurum) and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable and ductile metal. Chemically, gold is a transition metal and a group 11 element."
  },
  "Hg": {
    name: "Mercury",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10",
    valenceConfig: "[Xe] 6s2 4f14 5d10",
    electronegativity: 2,
    atomicRadius: 171,
    ionizationEnergy: 1007.1,
    electronAffinity: -48,
    oxidationStates: "",
    phase: "Liquid",
    meltingPoint: 234.321,
    boilingPoint: 629.88,
    density: 13.534,
    discoverer: "unknown, before 2000 BCE",
    summary: "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum (/haɪˈdrɑːrdʒərəm/). A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions for temperature and pressure; the only other element that is liquid under these conditions is bromine, though metals such as caesium, gallium, and rubidium melt just above room temperature."
  },
  "Tl": {
    name: "Thallium",
    category: "post-transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p1",
    valenceConfig: "[Xe] 6s2 4f14 5d10 6p1",
    electronegativity: 1.62,
    atomicRadius: 156,
    ionizationEnergy: 589.4,
    electronAffinity: 36.4,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 577,
    boilingPoint: 1746,
    density: 11.85,
    discoverer: "William Crookes",
    summary: "Thallium is a chemical element with symbol Tl and atomic number 81. This soft gray post-transition metal is not found free in nature. When isolated, it resembles tin, but discolors when exposed to air."
  },
  "Pb": {
    name: "Lead",
    category: "post-transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p2",
    valenceConfig: "[Xe] 6s2 4f14 5d10 6p2",
    electronegativity: 1.87,
    atomicRadius: 154,
    ionizationEnergy: 715.6,
    electronAffinity: 34.4204,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 600.61,
    boilingPoint: 2022,
    density: 11.34,
    discoverer: "Middle East",
    summary: "Lead (/lɛd/) is a chemical element in the carbon group with symbol Pb (from Latin:plumbum) and atomic number 82. Lead is a soft, malleable and heavy post-transition metal. Metallic lead has a bluish-white color after being freshly cut, but it soon tarnishes to a dull grayish color when exposed to air."
  },
  "Bi": {
    name: "Bismuth",
    category: "post-transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p3",
    valenceConfig: "[Xe] 6s2 4f14 5d10 6p3",
    electronegativity: 2.02,
    atomicRadius: 143,
    ionizationEnergy: 703,
    electronAffinity: 90.924,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 544.7,
    boilingPoint: 1837,
    density: 9.78,
    discoverer: "Claude François Geoffroy",
    summary: "Bismuth is a chemical element with symbol Bi and atomic number 83. Bismuth, a pentavalent post-transition metal, chemically resembles arsenic and antimony. Elemental bismuth may occur naturally, although its sulfide and oxide form important commercial ores."
  },
  "Po": {
    name: "Polonium",
    category: "post-transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p4",
    valenceConfig: "[Xe] 6s2 4f14 5d10 6p4",
    electronegativity: 2,
    atomicRadius: 135,
    ionizationEnergy: 812.1,
    electronAffinity: 136,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 527,
    boilingPoint: 1235,
    density: 9.196,
    discoverer: "Pierre Curie",
    summary: "Polonium is a chemical element with symbol Po and atomic number 84, discovered in 1898 by Marie Curie and Pierre Curie. A rare and highly radioactive element with no stable isotopes, polonium is chemically similar to bismuth and tellurium, and it occurs in uranium ores. Applications of polonium are few."
  },
  "At": {
    name: "Astatine",
    category: "metalloid",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p5",
    valenceConfig: "[Xe] 6s2 4f14 5d10 6p5",
    electronegativity: 2.2,
    atomicRadius: 127,
    ionizationEnergy: 899.003,
    electronAffinity: 233,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 575,
    boilingPoint: 610,
    density: 6.35,
    discoverer: "Dale R. Corson",
    summary: "Astatine is a very rare radioactive chemical element with the chemical symbol At and atomic number 85. It occurs on Earth as the decay product of various heavier elements. All its isotopes are short-lived; the most stable is astatine-210, with a half-life of 8.1 hours."
  },
  "Rn": {
    name: "Radon",
    category: "noble gas",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6",
    valenceConfig: "[Rn]",
    electronegativity: 2.2,
    atomicRadius: 120,
    ionizationEnergy: 1037,
    electronAffinity: -68,
    oxidationStates: "",
    phase: "Gas",
    meltingPoint: 202,
    boilingPoint: 211.5,
    density: 9.73,
    discoverer: "Friedrich Ernst Dorn",
    summary: "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas, occurring naturally as a decay product of radium. Its most stable isotope, 222Rn, has a half-life of 3.8 days."
  },
  "Fr": {
    name: "Francium",
    category: "alkali metal",
    block: "s",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s1",
    valenceConfig: "[Rn] 7s1",
    electronegativity: 0.79,
    atomicRadius: 348,
    ionizationEnergy: 380,
    electronAffinity: 46.89,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 300,
    boilingPoint: 950,
    density: 1.87,
    discoverer: "Marguerite Perey",
    summary: "Francium is a chemical element with symbol Fr and atomic number 87. It used to be known as eka-caesium and actinium K. It is the second-least electronegative element, behind only caesium. Francium is a highly radioactive metal that decays into astatine, radium, and radon."
  },
  "Ra": {
    name: "Radium",
    category: "alkaline earth metal",
    block: "s",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2",
    valenceConfig: "[Rn] 7s2",
    electronegativity: 0.9,
    atomicRadius: 283,
    ionizationEnergy: 509.3,
    electronAffinity: 9.6485,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1233,
    boilingPoint: 2010,
    density: 5.5,
    discoverer: "Pierre Curie",
    summary: "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals. Pure radium is almost colorless, but it readily combines with nitrogen (rather than oxygen) on exposure to air, forming a black surface layer of radium nitride (Ra3N2)."
  },
  "Ac": {
    name: "Actinium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 6d1",
    valenceConfig: "[Rn] 7s2 6d1",
    electronegativity: 1.1,
    atomicRadius: "N/A",
    ionizationEnergy: 499,
    electronAffinity: 33.77,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1500,
    boilingPoint: 3500,
    density: 10,
    discoverer: "Friedrich Oskar Giesel",
    summary: "Actinium is a radioactive chemical element with symbol Ac (not to be confused with the abbreviation for an acetyl group) and atomic number 89, which was discovered in 1899. It was the first non-primordial radioactive element to be isolated. Polonium, radium and radon were observed before actinium, but they were not isolated until 1902."
  },
  "Th": {
    name: "Thorium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 6d2",
    valenceConfig: "[Rn] 7s2 6d2",
    electronegativity: 1.3,
    atomicRadius: "N/A",
    ionizationEnergy: 587,
    electronAffinity: 112.72,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2023,
    boilingPoint: 5061,
    density: 11.724,
    discoverer: "Jöns Jakob Berzelius",
    summary: "Thorium is a chemical element with symbol Th and atomic number 90. A radioactive actinide metal, thorium is one of only two significantly radioactive elements that still occur naturally in large quantities as a primordial element (the other being uranium). It was discovered in 1828 by the Norwegian Reverend and amateur mineralogist Morten Thrane Esmark and identified by the Swedish chemist Jöns Jakob Berzelius, who named it after Thor, the Norse god of thunder."
  },
  "Pa": {
    name: "Protactinium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f2 6d1",
    valenceConfig: "[Rn] 7s2 5f2 6d1",
    electronegativity: 1.5,
    atomicRadius: "N/A",
    ionizationEnergy: 568,
    electronAffinity: 53.03,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1841,
    boilingPoint: 4300,
    density: 15.37,
    discoverer: "William Crookes",
    summary: "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray metal which readily reacts with oxygen, water vapor and inorganic acids. It forms various chemical compounds where protactinium is usually present in the oxidation state +5, but can also assume +4 and even +2 or +3 states."
  },
  "U": {
    name: "Uranium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f3 6d1",
    valenceConfig: "[Rn] 7s2 5f3 6d1",
    electronegativity: 1.38,
    atomicRadius: "N/A",
    ionizationEnergy: 597.6,
    electronAffinity: 50.94,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1405.3,
    boilingPoint: 4404,
    density: 19.1,
    discoverer: "Martin Heinrich Klaproth",
    summary: "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-white metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons."
  },
  "Np": {
    name: "Neptunium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f4 6d1",
    valenceConfig: "[Rn] 7s2 5f4 6d1",
    electronegativity: 1.36,
    atomicRadius: "N/A",
    ionizationEnergy: 604.5,
    electronAffinity: 45.85,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 912,
    boilingPoint: 4447,
    density: 20.45,
    discoverer: "Edwin McMillan",
    summary: "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element. Its position in the periodic table just after uranium, named after the planet Uranus, led to it being named after Neptune, the next planet beyond Uranus."
  },
  "Pu": {
    name: "Plutonium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f6",
    valenceConfig: "[Rn] 7s2 5f6",
    electronegativity: 1.28,
    atomicRadius: "N/A",
    ionizationEnergy: 584.7,
    electronAffinity: -48.33,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 912.5,
    boilingPoint: 3505,
    density: 19.816,
    discoverer: "Glenn T. Seaborg",
    summary: "Plutonium is a transuranic radioactive chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized. The element normally exhibits six allotropes and four oxidation states."
  },
  "Am": {
    name: "Americium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f7",
    valenceConfig: "[Rn] 7s2 5f7",
    electronegativity: 1.13,
    atomicRadius: "N/A",
    ionizationEnergy: 578,
    electronAffinity: 9.93,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1449,
    boilingPoint: 2880,
    density: 12,
    discoverer: "Glenn T. Seaborg",
    summary: "Americium is a radioactive transuranic chemical element with symbol Am and atomic number 95. This member of the actinide series is located in the periodic table under the lanthanide element europium, and thus by analogy was named after the Americas. Americium was first produced in 1944 by the group of Glenn T.Seaborg from Berkeley, California, at the metallurgical laboratory of University of Chicago."
  },
  "Cm": {
    name: "Curium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f7 6d1",
    valenceConfig: "[Rn] 7s2 5f7 6d1",
    electronegativity: 1.28,
    atomicRadius: "N/A",
    ionizationEnergy: 581,
    electronAffinity: 27.17,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1613,
    boilingPoint: 3383,
    density: 13.51,
    discoverer: "Glenn T. Seaborg",
    summary: "Curium is a transuranic radioactive chemical element with symbol Cm and atomic number 96. This element of the actinide series was named after Marie and Pierre Curie – both were known for their research on radioactivity. Curium was first intentionally produced and identified in July 1944 by the group of Glenn T. Seaborg at the University of California, Berkeley."
  },
  "Bk": {
    name: "Berkelium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f9",
    valenceConfig: "[Rn] 7s2 5f9",
    electronegativity: 1.3,
    atomicRadius: "N/A",
    ionizationEnergy: 601,
    electronAffinity: -165.24,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1259,
    boilingPoint: 2900,
    density: 14.78,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Berkelium is a transuranic radioactive chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series. It is named after the city of Berkeley, California, the location of the University of California Radiation Laboratory where it was discovered in December 1949."
  },
  "Cf": {
    name: "Californium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f10",
    valenceConfig: "[Rn] 7s2 5f10",
    electronegativity: 1.3,
    atomicRadius: "N/A",
    ionizationEnergy: 608,
    electronAffinity: -97.31,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1173,
    boilingPoint: 1743,
    density: 15.1,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Californium is a radioactive metallic chemical element with symbol Cf and atomic number 98. The element was first made in 1950 at the University of California Radiation Laboratory in Berkeley, by bombarding curium with alpha particles (helium-4 ions). It is an actinide element, the sixth transuranium element to be synthesized, and has the second-highest atomic mass of all the elements that have been produced in amounts large enough to see with the unaided eye (after einsteinium)."
  },
  "Es": {
    name: "Einsteinium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f11",
    valenceConfig: "[Rn] 7s2 5f11",
    electronegativity: 1.3,
    atomicRadius: "N/A",
    ionizationEnergy: 619,
    electronAffinity: -28.6,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1133,
    boilingPoint: 1269,
    density: 8.84,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Einsteinium is a synthetic element with symbol Es and atomic number 99. It is the seventh transuranic element, and an actinide. Einsteinium was discovered as a component of the debris of the first hydrogen bomb explosion in 1952, and named after Albert Einstein."
  },
  "Fm": {
    name: "Fermium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f12",
    valenceConfig: "[Rn] 7s2 5f12",
    electronegativity: 1.3,
    atomicRadius: "N/A",
    ionizationEnergy: 627,
    electronAffinity: 33.96,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1800,
    boilingPoint: null,
    density: null,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Fermium is a synthetic element with symbol Fm and atomic number 100. It is a member of the actinide series. It is the heaviest element that can be formed by neutron bombardment of lighter elements, and hence the last element that can be prepared in macroscopic quantities, although pure fermium metal has not yet been prepared."
  },
  "Md": {
    name: "Mendelevium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f13",
    valenceConfig: "[Rn] 7s2 5f13",
    electronegativity: 1.3,
    atomicRadius: "N/A",
    ionizationEnergy: 635,
    electronAffinity: 93.91,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1100,
    boilingPoint: null,
    density: null,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Mendelevium is a synthetic element with chemical symbol Md (formerly Mv) and atomic number 101. A metallic radioactive transuranic element in the actinide series, it is the first element that currently cannot be produced in macroscopic quantities through neutron bombardment of lighter elements. It is the antepenultimate actinide and the ninth transuranic element."
  },
  "No": {
    name: "Nobelium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14",
    valenceConfig: "[Rn] 7s2 5f14",
    electronegativity: 1.3,
    atomicRadius: "N/A",
    ionizationEnergy: 642,
    electronAffinity: -223.22,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1100,
    boilingPoint: null,
    density: null,
    discoverer: "Joint Institute for Nuclear Research",
    summary: "Nobelium is a synthetic chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science. A radioactive metal, it is the tenth transuranic element and is the penultimate member of the actinide series."
  },
  "Lr": {
    name: "Lawrencium",
    category: "actinide",
    block: "f",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 7p1",
    valenceConfig: "[Rn] 7s2 5f14 7p1",
    electronegativity: 1.3,
    atomicRadius: "N/A",
    ionizationEnergy: 470,
    electronAffinity: -30.04,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 1900,
    boilingPoint: null,
    density: null,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Lawrencium is a synthetic chemical element with chemical symbol Lr (formerly Lw) and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements. A radioactive metal, lawrencium is the eleventh transuranic element and is also the final member of the actinide series."
  },
  "Rf": {
    name: "Rutherfordium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d2",
    valenceConfig: "[Rn] 7s2 5f14 6d2",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: 580,
    electronAffinity: null,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 2400,
    boilingPoint: 5800,
    density: 23.2,
    discoverer: "Joint Institute for Nuclear Research",
    summary: "Rutherfordium is a chemical element with symbol Rf and atomic number 104, named in honor of physicist Ernest Rutherford. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, 267Rf, has a half-life of approximately 1.3 hours. In the periodic table of the elements, it is a d - block element and the second of the fourth - row transition elements."
  },
  "Db": {
    name: "Dubnium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d3",
    valenceConfig: "[Rn] 7s2 5f14 6d3",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: null,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: null,
    boilingPoint: null,
    density: 29.3,
    discoverer: "Joint Institute for Nuclear Research",
    summary: "Dubnium is a chemical element with symbol Db and atomic number 105. It is named after the town of Dubna in Russia (north of Moscow), where it was first produced. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, dubnium-268, has a half-life of approximately 28 hours."
  },
  "Sg": {
    name: "Seaborgium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d4",
    valenceConfig: "[Rn] 7s2 5f14 6d4",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: null,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: null,
    boilingPoint: null,
    density: 35,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Seaborgium is a synthetic element with symbol Sg and atomic number 106. Its most stable isotope 271Sg has a half-life of 1.9 minutes. A more recently discovered isotope 269Sg has a potentially slightly longer half-life (ca."
  },
  "Bh": {
    name: "Bohrium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d5",
    valenceConfig: "[Rn] 7s2 5f14 6d5",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: null,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: null,
    boilingPoint: null,
    density: 37.1,
    discoverer: "Gesellschaft für Schwerionenforschung",
    summary: "Bohrium is a chemical element with symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, 270Bh, has a half-life of approximately 61 seconds."
  },
  "Hs": {
    name: "Hassium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d6",
    valenceConfig: "[Rn] 7s2 5f14 6d6",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: null,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 126,
    boilingPoint: null,
    density: 40.7,
    discoverer: "Gesellschaft für Schwerionenforschung",
    summary: "Hassium is a chemical element with symbol Hs and atomic number 108, named after the German state of Hesse. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, 269Hs, has a half-life of approximately 9.7 seconds, although an unconfirmed metastable state, 277mHs, may have a longer half-life of about 130 seconds. More than 100 atoms of hassium have been synthesized to date."
  },
  "Mt": {
    name: "Meitnerium",
    category: "unknown, probably transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d7",
    valenceConfig: "[Rn] 7s2 5f14 6d7",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: null,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: null,
    boilingPoint: null,
    density: 37.4,
    discoverer: "Gesellschaft für Schwerionenforschung",
    summary: "Meitnerium is a chemical element with symbol Mt and atomic number 109. It is an extremely radioactive synthetic element (an element not found in nature that can be created in a laboratory). The most stable known isotope, meitnerium-278, has a half-life of 7.6 seconds."
  },
  "Ds": {
    name: "Darmstadtium",
    category: "unknown, probably transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d8",
    valenceConfig: "[Rn] 7s2 5f14 6d8",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: null,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: null,
    boilingPoint: null,
    density: 34.8,
    discoverer: "Gesellschaft für Schwerionenforschung",
    summary: "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is an extremely radioactive synthetic element. The most stable known isotope, darmstadtium-281, has a half-life of approximately 10 seconds."
  },
  "Rg": {
    name: "Roentgenium",
    category: "unknown, probably transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d9",
    valenceConfig: "[Rn] 7s2 5f14 6d9",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: 151,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: null,
    boilingPoint: null,
    density: 28.7,
    discoverer: "Gesellschaft für Schwerionenforschung",
    summary: "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is an extremely radioactive synthetic element (an element that can be created in a laboratory but is not found in nature); the most stable known isotope, roentgenium-282, has a half-life of 2.1 minutes. Roentgenium was first created in 1994 by the GSI Helmholtz Centre for Heavy Ion Research near Darmstadt, Germany."
  },
  "Cn": {
    name: "Copernicium",
    category: "transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10",
    valenceConfig: "[Rn] 7s2 5f14 6d10",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: null,
    oxidationStates: "",
    phase: "Liquid",
    meltingPoint: null,
    boilingPoint: 3570,
    density: 14.0,
    discoverer: "Gesellschaft für Schwerionenforschung",
    summary: "Copernicium is a chemical element with symbol Cn and atomic number 112. It is an extremely radioactive synthetic element that can only be created in a laboratory. The most stable known isotope, copernicium-285, has a half-life of approximately 29 seconds, but it is possible that this copernicium isotope may have a nuclear isomer with a longer half-life, 8.9 min."
  },
  "Nh": {
    name: "Nihonium",
    category: "unknown, probably transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p1",
    valenceConfig: "[Rn] 7s2 5f14 6d10 7p1",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: 66.6,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 700,
    boilingPoint: 1430,
    density: 16,
    discoverer: "RIKEN",
    summary: "Nihonium is a chemical element with atomic number 113. It has a symbol Nh. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and is extremely radioactive; its most stable known isotope, nihonium-286, has a half-life of 20 seconds."
  },
  "Fl": {
    name: "Flerovium",
    category: "post-transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p2",
    valenceConfig: "[Rn] 7s2 5f14 6d10 7p2",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: null,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 340,
    boilingPoint: 420,
    density: 14,
    discoverer: "Joint Institute for Nuclear Research",
    summary: "Flerovium is a superheavy artificial chemical element with symbol Fl and atomic number 114. It is an extremely radioactive synthetic element. The element is named after the Flerov Laboratory of Nuclear Reactions of the Joint Institute for Nuclear Research in Dubna, Russia, where the element was discovered in 1998."
  },
  "Mc": {
    name: "Moscovium",
    category: "unknown, probably post-transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p3",
    valenceConfig: "[Rn] 7s2 5f14 6d10 7p3",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: 35.3,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 670,
    boilingPoint: 1400,
    density: 13.5,
    discoverer: "Joint Institute for Nuclear Research",
    summary: "Moscovium is the name of a synthetic superheavy element in the periodic table that has the symbol Mc and has the atomic number 115. It is an extremely radioactive element; its most stable known isotope, moscovium-289, has a half-life of only 220 milliseconds. It is also known as eka-bismuth or simply element 115."
  },
  "Lv": {
    name: "Livermorium",
    category: "unknown, probably post-transition metal",
    block: "d",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p4",
    valenceConfig: "[Rn] 7s2 5f14 6d10 7p4",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: 74.9,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 709,
    boilingPoint: 1085,
    density: 12.9,
    discoverer: "Joint Institute for Nuclear Research",
    summary: "Livermorium is a synthetic superheavy element with symbol Lv and atomic number 116. It is an extremely radioactive element that has only been created in the laboratory and has not been observed in nature. The element is named after the Lawrence Livermore National Laboratory in the United States, which collaborated with the Joint Institute for Nuclear Research in Dubna, Russia to discover livermorium in 2000."
  },
  "Ts": {
    name: "Tennessine",
    category: "unknown, probably metalloid",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p5",
    valenceConfig: "[Rn] 7s2 5f14 6d10 7p5",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: 165.9,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: 723,
    boilingPoint: 883,
    density: 7.17,
    discoverer: "Joint Institute for Nuclear Research",
    summary: "Tennessine is a superheavy artificial chemical element with an atomic number of 117 and a symbol of Ts. Also known as eka-astatine or element 117, it is the second-heaviest known element and penultimate element of the 7th period of the periodic table. As of 2016, fifteen tennessine atoms have been observed: six when it was first synthesized in 2010, seven in 2012, and two in 2014."
  },
  "Og": {
    name: "Oganesson",
    category: "unknown, predicted to be noble gas",
    block: "p",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p6",
    valenceConfig: "[Rn] 7s2 5f14 6d10 7p6",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: 5.40318,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: null,
    boilingPoint: 350,
    density: 4.95,
    discoverer: "Joint Institute for Nuclear Research",
    summary: "Oganesson is IUPAC's name for the transactinide element with the atomic number 118 and element symbol Og. It is also known as eka-radon or element 118, and on the periodic table of the elements it is a p-block element and the last one of the 7th period. Oganesson is currently the only synthetic member of group 18."
  },
  "Uue": {
    name: "Ununennium",
    category: "unknown, but predicted to be an alkali metal",
    block: "s",
    electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2 5f14 6d10 7p6 8s1",
    valenceConfig: "[Rn] 7s2 5f14 6d10 7p6 8s1",
    electronegativity: null,
    atomicRadius: "N/A",
    ionizationEnergy: null,
    electronAffinity: 63.87,
    oxidationStates: "",
    phase: "Solid",
    meltingPoint: null,
    boilingPoint: 630,
    density: 3,
    discoverer: "GSI Helmholtz Centre for Heavy Ion Research",
    summary: "Ununennium, also known as eka-francium or simply element 119, is the hypothetical chemical element with symbol Uue and atomic number 119. Ununennium and Uue are the temporary systematic IUPAC name and symbol respectively, until a permanent name is decided upon. In the periodic table of the elements, it is expected to be an s-block element, an alkali metal, and the first element in the eighth period."
  },
};
